/*
 * This C++ source file was generated by the Gradle 'init' task.
 */
#ifndef MAIN_H
#define MAIN_H

#include <string.h>
#include <string>

namespace c_lab {
    class Greeter {
        public:
        std::string greeting();
    };
};

#endif
